---

plugins:
  # https://github.com/babel/eslint-plugin-babel
  - babel
  - import

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true

extends:
  - 'airbnb-base'

rules:
  no-console: 0